######################################################################
# Automatically generated by qmake (3.0) Sat May 21 22:28:33 2016
######################################################################

TEMPLATE = app
TARGET = mathchallenge
INCLUDEPATH += .

# Input
HEADERS += main_window.hpp
FORMS += main_window.ui
SOURCES += main.cpp main_window.cpp
QMAKE_CXXFLAGS += -std=c++11
CONFIG += debug
